#!/usr/bin/env bash
# -------------------------------------------------------------------
# sync-network-configs.sh — Propagate .env network IPs into config files
#
# Syncs: SERVER_IP, PIHOLE_IP, MACVLAN_GATEWAY, BASE_DOMAIN
# Targets: pihole/dnsmasq.d/05-home-local.conf, dashy/conf.yaml, nginx/conf.d/home-server.conf
# -------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${ENV_FILE:-${REPO_ROOT}/.env}"

PIHOLE_CONF="${REPO_ROOT}/pihole/dnsmasq.d/05-home-local.conf"
DASHY_CONF="${REPO_ROOT}/dashy/conf.yaml"
NGINX_CONF="${REPO_ROOT}/nginx/conf.d/home-server.conf"
SSL_SNIPPET="${REPO_ROOT}/nginx/snippets/ssl-common.conf"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: env file not found at ${ENV_FILE}"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

if [[ -z "${SERVER_IP:-}" ]]; then
  echo "Error: SERVER_IP is not set in ${ENV_FILE}"
  exit 1
fi

BASE_DOMAIN="${BASE_DOMAIN:-home.local}"
BASE_DOMAIN_ESC="${BASE_DOMAIN//&/\\&}"
CA_DOWNLOAD_FILENAME="${BASE_DOMAIN}-ca.crt"
CA_DOWNLOAD_FILENAME_ESC="${CA_DOWNLOAD_FILENAME//&/\\&}"

# --- Pi-hole dnsmasq: regenerate from .env so it always matches user preferences ---
cat > "${PIHOLE_CONF}" <<EOF
# Pi-hole local DNS records for reverse-proxied apps.
# Auto-generated by scripts/setup/sync-network-configs.sh from .env
address=/${BASE_DOMAIN}/${SERVER_IP}
address=/dashy.${BASE_DOMAIN}/${SERVER_IP}
address=/vscode.${BASE_DOMAIN}/${SERVER_IP}
address=/portainer.${BASE_DOMAIN}/${SERVER_IP}
address=/glances.${BASE_DOMAIN}/${SERVER_IP}
address=/nextcloud.${BASE_DOMAIN}/${SERVER_IP}
address=/jellyfin.${BASE_DOMAIN}/${SERVER_IP}
address=/qbittorrent.${BASE_DOMAIN}/${SERVER_IP}
address=/immich.${BASE_DOMAIN}/${SERVER_IP}
address=/files.${BASE_DOMAIN}/${SERVER_IP}
# address=/orca.${BASE_DOMAIN}/${SERVER_IP}
EOF
echo "✅ ${PIHOLE_CONF} regenerated from .env"

# --- Domain sync in app configs ---
if [[ -f "${DASHY_CONF}" ]]; then
  sed -E -i "s|home\.local|${BASE_DOMAIN_ESC}|g" "${DASHY_CONF}"
fi
if [[ -f "${NGINX_CONF}" ]]; then
  sed -E -i "s|home\.local|${BASE_DOMAIN_ESC}|g" "${NGINX_CONF}"
  sed -E -i "s|Content-Disposition 'attachment; filename=\"[^\"]+\"' always;|Content-Disposition 'attachment; filename=\"${CA_DOWNLOAD_FILENAME_ESC}\"' always;|g" "${NGINX_CONF}"
fi
echo "✅ Domain sync → BASE_DOMAIN=${BASE_DOMAIN}"

# --- Keep TLS and Nextcloud domain settings aligned with BASE_DOMAIN ---
if [[ -f "${SSL_SNIPPET}" ]]; then
  cat > "${SSL_SNIPPET}" <<EOF
ssl_certificate /etc/nginx/certs/${BASE_DOMAIN}.crt;
ssl_certificate_key /etc/nginx/certs/${BASE_DOMAIN}.key;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
ssl_prefer_server_ciphers off;
EOF
  echo "✅ ${SSL_SNIPPET} certificate paths synced"
fi

if grep -qE '^NEXTCLOUD_TRUSTED_DOMAINS=' "${ENV_FILE}"; then
  sed -E -i "s|^NEXTCLOUD_TRUSTED_DOMAINS=.*|NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${BASE_DOMAIN_ESC}|" "${ENV_FILE}"
  echo "✅ ${ENV_FILE} NEXTCLOUD_TRUSTED_DOMAINS synced"
fi

# --- Dashy conf: update IP-based URLs ---
if [[ -f "${DASHY_CONF}" ]]; then
  # Pi-hole admin URL
  if [[ -n "${PIHOLE_IP:-}" ]]; then
    sed -E -i "s|(url:[[:space:]]*)http://[0-9.]+/admin|\1http://${PIHOLE_IP}/admin|" "${DASHY_CONF}"
    echo "✅ ${DASHY_CONF} Pi-hole → PIHOLE_IP=${PIHOLE_IP}"
  fi

  # Primary router (TPLink) — identified by dashy id "4_746_tplink"
  if [[ -n "${MACVLAN_GATEWAY:-}" ]]; then
    awk -v gw="${MACVLAN_GATEWAY}" '
      /url:/ { url_line = NR; url_content = $0 }
      /id: 4_746_tplink/ && url_line == NR-2 {
        sub(/http:\/\/[0-9.]+/, "http://" gw, url_content)
        lines[url_line] = url_content
      }
      { lines[NR] = ( lines[NR] ? lines[NR] : $0 ) }
      END { for (i=1; i<=NR; i++) print lines[i] }
    ' "${DASHY_CONF}" > "${DASHY_CONF}.tmp" && mv "${DASHY_CONF}.tmp" "${DASHY_CONF}"
    echo "✅ ${DASHY_CONF} router → MACVLAN_GATEWAY=${MACVLAN_GATEWAY}"
  fi
fi
