ssl_certificate /etc/nginx/certs/homepi.local.crt;
ssl_certificate_key /etc/nginx/certs/homepi.local.key;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
ssl_prefer_server_ciphers off;
